#! /usr/bin/env python3

"""
A Python script.

This script is useless.

CC0
"""

import locale
import sys


def do_nothing(arg):
    """Useless function."""
    pass


if __name__ == "__main__":
    locale.setlocale(locale.LC_ALL, "")
    sys.exit(None)
